### ISSUE TITLE
[Bug]: Actionable Notification Inline buttons displaying incorrectly 

### ISSUE THREAD

**Issue by ellamathewsonibm** [carbon-design-system/carbon#15320]
### Package

@carbon/react

### Browser

Chrome

### Package version

v1.42.1

### React version

v18.2.0

### Description

Actionable Notification component with inline prop set to true displays the Actionable Button stacked above the 'x' close button, when these buttons should be inline vertically

<img width="1714" alt="Screenshot 2023-12-04 at 5 19 06 PM" src="https://github.com/carbon-design-system/carbon/assets/152651072/9051d840-8394-4d38-98d2-f09285990cf2">

### Reproduction/example

https://react.carbondesignsystem.com/?path=/story/components-notifications-actionable--playground&args=kind:info;lowContrast:!true;statusIconDescription:in;inline:!true

### Steps to reproduce

Open Actionable Notification component and set prop `inline` to `true`. See Action button displayed above 'x' close button

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Application/PAL

w3 Carbon

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by kuri-sun** [comment]
Hello! I would love to work on this issue! May I?

**Comment by kuri-sun** [comment]
Hi @ellamathewsonibm and everyone!
I believe that this bug was fixed in [this PR](https://github.com/carbon-design-system/carbon/pull/15314).
So if that is correct, I think we can close this issue!
Thank you!

**Comment by ellamathewsonibm** [comment]
> Hi @ellamathewsonibm and everyone! I believe that this bug was fixed in [this PR](https://github.com/carbon-design-system/carbon/pull/15314). If that is correct, I think we can close this issue! Thank you!

Hello! Yes, this is the same issue as the one in the PR you linked. This can be closed. Thank you!

**Comment by ellamathewsonibm** [comment]
@kuri-sun Hello! Actually, I'm still seeing this issue on the latest version (v1.44.0). Is this the correct version for the fix?

**Comment by tay1orjones** [comment]
https://github.com/carbon-design-system/carbon/pull/15314 will be released in our next release, [slated for this week](https://github.com/carbon-design-system/carbon/wiki/Release-radar). Thanks for reporting this, and thanks for the quick fix @kuri-sun!

**Comment by tay1orjones** [comment]
Duplicate of https://github.com/carbon-design-system/carbon/pull/15314
