### ISSUE TITLE
Button - experimental component (feedback from review)

### ISSUE THREAD

**Issue by asudoh** [carbon-design-system/carbon#1865]
From @laurenmrice on Nov 15, 2018 - Not sure if it's still valid, though:

- [x] Create 48px button style option (to be used when there are 40 px fields option)
- [ ] Ghost button icon relationship 
     - [x] Ghost button has an opacity layer on it that needs to be taken off
     - [ ]  Make fixed 16px padding on both ends across the board

**Comment by laurenmrice** [comment]
@asudoh still valid

**Comment by jendowns** [comment]
Quick question since this issue seems related: 

On the Security team, we've seen a lot of designs with very large buttons with icons in the lower right corner. A quick example I can think of is on the current Carbon X site (though those buttons are even bigger than the ones I'm thinking of): https://next.carbondesignsystem.com/

![screen shot 2019-02-19 at 3 25 14 pm](https://user-images.githubusercontent.com/9057921/53048583-b7641000-345a-11e9-932e-8833c25aeb11.png)

Was Carbon considering creating a standardized Large and maybe even X-Large button variation? It would be especially helpful for the React components, from our perspective.

**Comment by laurenmrice** [comment]
@jendowns Eventually we will be designing a series of these larger fluid buttons. As of right now we only designed the one to one version of current Carbon (fixed buttons).

**Comment by emyarod** [comment]
from what I can tell the points in the original ticket have already been addressed, unless I am misunderstanding them

**Comment by asudoh** [comment]
@laurenmrice Would you agree with @emyarod's assessment that everything in this issue has been addressed...? Thanks!

**Comment by laurenmrice** [comment]
@emyarod The ghost button needs to have 16 px in these areas as speced. Right now on the website the icon is still hanging far right.

![artboard](https://user-images.githubusercontent.com/43969356/53190268-cec40a00-35ce-11e9-9276-2e54478cc8af.png)

**Comment by emyarod** [comment]
@laurenmrice I see, so we want to remove the minimum width rule from only our ghost buttons, is that right? I believe the reason why it appears that the icons are very far to the right in the ghost buttons is because they still have a minimum width value that's carried over from our other buttons, and the icon is just positioned 16px left of the far right edge

**Comment by laurenmrice** [comment]
@emyarod Yes, correct ^

**Comment by asudoh** [comment]
CC @tw15egan

**Comment by jeanservaas** [comment]
This issue is being tracked here now:
https://github.com/IBM/carbon-components/issues/1928
