### ISSUE TITLE
[Bug]: Popover content is unclickable

### ISSUE THREAD

**Issue by kWcislo98** [carbon-design-system/carbon#20271]
### Package

@carbon/react

### Browser

Chrome

### Package version

v1.89.0

### Description

Popover component doesn't work as expected. When user opens Popover content, he's not able to select any option. Whole content is being hidden after user clicks anywhere.

### Reproduction/example

https://react.carbondesignsystem.com/?path=/story/components-popover--tab-tip

### Steps to reproduce

1. Open popover content
2. Click any option in a content
3. Whole content disappears

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [ ] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by heloiselui** [comment]
It was fixed at some point in [this PR](https://github.com/carbon-design-system/carbon/pull/20022) but there must have been a breaking change.

**Comment by kWcislo98** [comment]
@heloiselui @2nikhiltom  is this issue fixed? Which version contain the fix?

**Comment by kWcislo98** [comment]
I'm using v1.97.0 and it's still broken.

https://github.com/user-attachments/assets/3389897a-0348-47ed-8d11-a07dcf7af103
