### ISSUE TITLE
React Storybook: Overflow menu does not open

### ISSUE THREAD

**Issue by asudoh** [carbon-design-system/carbon#4019]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

Overflow menu does not open at: http://react.carbondesignsystem.com/?path=/story/overflowmenu--basic

> Is this issue related to a specific component?

Yes, `<OverflowMenu>`

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Expected to see the menu open.

> What browser are you working in?

Chrome 77

> What version of the Carbon Design System are you using?

`10.6.0`

**Comment by emyarod** [comment]
this was resolved in https://github.com/carbon-design-system/carbon/pull/3966 but the netlify build is outdated. it's still showing the old code from https://github.com/carbon-design-system/carbon/pull/3918/files#diff-38fd15dc34d2ebce060092f86b61f09a

**Comment by asudoh** [comment]
Thanks @emyarod - Does this mean we should simply deploy the latest to `react.carbondesignsystem.com`?

**Comment by emyarod** [comment]
@asudoh yes that should fix the storybook issue, although it doesn't look like that fix has been released yet

**Comment by asudoh** [comment]
OK thanks @emyarod - Let's close it for now - We can reopen if we see the problem persists.

**Comment by kinueng** [comment]
Just checked the website.  Dropdown menu is working now
