### ISSUE TITLE
[DataTable]: the table content doesn't re-render the changes when I update rows propos

### ISSUE THREAD

**Issue by HafidZiti** [carbon-design-system/carbon#7956]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

The table cells doesn't reflect the changes, when I updated an item in rows(DataTable propos). I can see the changes just when I add an extra item, or remove one.

React codeSandbox : https://codesandbox.io/s/carbon-datatable-render-issue-zt2gc?file=/index.js

**Comment by emyarod** [comment]
most likely you would need to implement this with a [custom state manager](https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/custom-data-table-state-manager), meaning you would be implementing that logic using Carbon table primitives like `Table`, `TableHead`, `TableRow`,  etc. rather than using the built in state manager in `DataTable`, if that makes sense

**Comment by HafidZiti** [comment]
> most likely you would need to implement this with a [custom state manager](https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/custom-data-table-state-manager), meaning you would be implementing that logic using Carbon table primitives like `Table`, `TableHead`, `TableRow`, etc. rather than using the built in state manager in `DataTable`, if that makes sense
 
 That's what I've done, and it works, it's just because in our project we often use `DataTable`, it's less lines of code :) 
 Thanks!

**Comment by tw15egan** [comment]
Closing as resolved, but feel free to reopen if there is anything else you'd like us to take a look at! 👍🏻

**Comment by galilmori** [comment]
@tw15egan @emyarod  i am not sure that this is resolved in datatable per se. if we need to create our own custom datatable to manage the most basic state update than you should not propose the datatable component in the first place this is basic react workflow.... please reopen and fix this

**Comment by emyarod** [comment]
you're right that it isn't resolved specifically in the DataTable component due to its built in state manager, and I think the custom table route should be the way to go in the long run. I believe we should view the DataTable like ModalWrapper in that it is more of an example than a consumable component. Because there are many different use cases for managing table state, supporting every possible use case in DataTable would be extremely complex. so ultimately I think the solution is to allow consumers to use implement their own custom state manager with the Carbon table primitives as shown in the sandbox above. that being said I'm interested in hearing more opinions about this

**Comment by galilmori** [comment]
@emyarod I agree that you cannot predict every usecase of a table.  But following up the data changes in the rows coming from props  in a table seems to me as the most elementary use of a data table. or else what use do u see for this component?
Only to display static row data? Or just an example?

If the carbon dev team sees it as an example rather than a generic component users should be spared of loosing time using it in their implementation, therefore imho this component should be in the examples section rather than generic components. This component is the first thing that users see as a table in the documentation and not the custom table components causing users to think that this is the recommended interface...

**Comment by emyarod** [comment]
yeah I don't disagree with you on your comments. with respect to relegating the DataTable component to a stateful example like ModalWrapper I am speaking mostly from my perspective (and I should clarify that my previous comment is my opinion on the restrictive DataTable state manager vs custom data table). where the team stands on the direction of stateful DataTable vs table primitives is not clear yet but our documentation should reflect whatever the consensus is
